language: node_js
node_js:
- '8'
- '10'
branches:
  only:
  - master
  - develop
cache:
  yarn: true
  directories:
  - ".npm"
  - node_modules

addons:
  sonarcloud:
    organization: "kevinhassan-github"
    token:
      secure: "YTnMdPnt4cH84iID9HaoN4Rb
WgQyLSMrTODeefE9RuFkwljL253F/UvimbC
OIJDMgDiIzvVg38ZiKku6VCSBYPI7LVme7/jwleEaJOPodhzHTKX6fV9zfnIyiedeJSYax
MEpqpD+Pu1RXsVObrSS2T3h7JHZ1Vj8o3XeYCKVAwQcrPSwRgW7+QIQzVxaCM6v/q2DxNt0to2gTTZvFQfjMWi3x1mhz9RQoZFxcS2Ebo
JsfQP8eHG4XhdIVR0AmP0IPDsE4SJMsuEkxdfPakuln6n7IBi1JcwrtQOykncVXk1kmdGt
CrDkinLB0TodZBxT+bvVv0gTDeaANqBjtEtsoWpY9VjMAKO+piQgexiLA77MpwpW4X+P/V
g0jNl4ZlNEMEKud209gUrSlIqUw0THeiR02YZ5JqUnPVzybBBGWQ3Of4jlwEg+Fkl/X2Lt
fP/Sg6UbxTRAEcrYll6jY/gmF5QOs7jiYS++vcL9oHWv1QEhTnBZfLLeT7gblFXEyMGDW7JxUQFL6h+xqyn3uF8oh3PfS4L0TsVPgrewrKh3cIEIvX2FHH4777FoGzuy9wQczhH0/xTMzX8bSPh3lq3eDAzQ0EIaKacr01OmsI5Ez55SPkC0Ev4jPXBH/CxSZ35sA+Pc0ImjLNzpMTt1kBbxrsX6wX3P9hl3hgGfUohV1Jo="

services:
- mongodb

env:
- TEST_DIR=./client
- TEST_DIR=./server

before_script:
- cd $TEST_DIR
- npm install
- npm test

notifications:
  email: false
  slack:
    secure: PnObvvDhdayHXHvS+QkYEnU5pV9hs9Nsb5PNZce9ZlxC7DMSmg6e2d3/vD8Eq4Y7NUARQJWx6t3WV6c1D5tQA/pH0uqNCbfqRa5hVMMWddLY6+jMJRAJKnp9rgf3qugif+TllJ7/+jFXC/2hQEmL4lxIotRxtte7PA/8YhgsQIHgVkh3sBmiK1n1rPBL8jjY+YSW3VyoeqCnv4JPCa4HpmUEmckKF5DNHNsxajD9SRDRFD9EYZFaV4o65yePaedCbC4EAF2YHmB+vJ6k5vT5/6sjPrrgWmD04tVT94VMb0HHSlls2cjrw3PLPnX9bTD5m7eDSIiZj9zMPxKPHtDwhvIzBRv4pHNZmr7aAg+nPK0TnMDYas+Ls6s0M9b4644VTk7Ni2kW7zIJVE8RuS7/l7137Mop+sw3xWMHqBN6YjG5D3tnrSGC7os6ajVYfCAd0D3/1YHiIAn3sky+2Pd5SFs8cIMOuXV2NBx17ZO4E5lPU2U4LVqbmpmJTqonLLgSg+43La8CLvAMeXLfwE8JcaXKufDkpsRlznce7+L6/yqRM62POe0x5Rb8hpDO+wIVv7ZddbAv4qKQBANaYq/yhpfxlwUWU2DkQE6TpUZvsW428+kbSyE1WLPSEtlYzIfRTZ+jc1kyi9X7AP6XW+RQ6QEbQMsW/56vxbSeZJY5I8Q=
