
language: node_js
node_js:
  - '8'
  - '10'
branches:
  only:
    - master
    - develop
cache:
  yarn: true
  directories:
    - .npm
services: [
  mongodb
]
script: [
  cd server
  npm test
  cd ../client
  npm test
]